# use the official rust image, based on debian
# see https://hub.docker.com/_/rust
image: rust:1.21-stretch

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  DOCKER_HOST: tcp://localhost:2375


services:
  - dcr.buyme360.com/devops/docker:dind

cache:
  untracked: true

build:
  stage: build
  script:
    - cargo build
    - cargo build --release
  artifacts:
    paths:
      - target/debug/blockscape
      - target/release/blockscape
    expire_in: 2 days

  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time

pages:
  script:
    - cargo doc
    - mkdir public
    - cp -R target/doc/* public
  artifacts:
    paths:
      - public
  only:
    - master

# run tests using the binary built before
test:
  stage: test
  script:
    - cargo test
    - cargo test -p blockscape_core
  
package:
  image: dcr.buyme360.com/devops/docker:latest
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  dependencies:
    - build
    