# use the official rust image, based on debian
# see https://hub.docker.com/_/rust
image: rust:1.20

build:
  stage: build
  script:
    - cargo build

  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  cache:
    paths:
      - "target"

pages:
  stage: deploy
  script:
    - cargo doc
  artifacts:
    paths:
      - target/doc
  only:
    - master

# run tests using the binary built before
test:
  stage: test
  script:
    - cargo test