[package]
name = "blockscape"
version = "0.0.1"
authors = ["Daniel Beal <git@danb.email.com>", "Matthew Conover <matt@xram.co>"]

[dependencies]
blockscape_core = { path = "core" }

[[bin]]
path = "client/main.rs"
name = "blockscape"