apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: blockscape-explorer-${CI_COMMIT_REF_SLUG}
  namespace: blockscape
spec:
  secretName: ${CI_COMMIT_REF_SLUG}-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: explorer-${CI_COMMIT_REF_SLUG}.blockscape.xram.co
  dnsNames:
  - explorer-${CI_COMMIT_REF_SLUG}.blockscape.xram.co
  acme:
    config:
    - http01: {}
      domains:
      - explorer-${CI_COMMIT_REF_SLUG}.blockscape.xram.co
