version: '3.3'

services:
    blockscape_1:
        image: dcr.buyme360.com/plu-capstone/blockscape:latest

        networks:
            - net

        command: /blockscape -h blockscape_1 --seed-node blockscape_2:35653 -F
    
    blockscape_2:
        image: dcr.buyme360.com/plu-capstone/blockscape:latest

        networks:
            - net

        command: /blockscape -h blockscape_2 -F # --seed-node blockscape_1:35653

    blockscape_3:
        image: dcr.buyme360.com/plu-capstone/blockscape:latest

        networks:
            - net

        command: /blockscape -h blockscape_3 --seed-node blockscape_1:35653 -F

networks:
    net:
