version: '3.3'

services:
    blockscape_1:
        image: dcr.buyme360.com/plu-capstone/blockscape:latest

        networks:
            - net

        command: /blockscape -h blockscape_1 --seed-node tcp:blockscape_2:35653 --rpcbind 0.0.0.0 -F --force-forge
    
    blockscape_2:
        image: dcr.buyme360.com/plu-capstone/blockscape:latest

        networks:
            - net

        command: /blockscape -h blockscape_2 -F # --seed-node blockscape_1:35653

    blockscape_3:
        image: dcr.buyme360.com/plu-capstone/blockscape:latest

        networks:
            - net

        command: /bin/bash -c 'sleep 20 && /blockscape -h blockscape_3 --seed-node tcp:blockscape_1:35653 -F'

    blockscape_explorer:
        image: dcr.buyme360.com/plu-capstone/blockscape-explorer:master

        networks:
            - net
        
        command: /bin/bash -c 'echo "{\"rpc\":{\"host\":\"blockscape_1\",\"port\":8356}}" > config.json && ts-node lib/server.ts'

        ports:
            - 8000:3000

networks:
    net:
